In [915]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [916]:
df=pd.read_excel("C:/Users/ASUS/r-ecommerce_ raw_data.xlsx")
df

,Order_ID,Line_ID,Event_Version,Customer_ID,Master_Customer_ID,Transaction_ID,Visitor_ID,Session_ID,Event_Type,Order_TS,...,Promotion_Status,Campaign_ID,Return_Reason_Code,Tracking_ID,Carrier,Delivery_Status,Email,Phone_Number,Device,Acquisition_Channel
0,ORD-1098,L2,3,CUST-053,CUST-053,TXN-55514836,VIS-58611,NaN,payment_success,07/19/2026 02:45 PM PST,...,Applied,CMP-002,NaN,TRK279355399,fedex,Delivered,sara53@example.com,8016659593,mobile,organic
1,ORD-1082,L1,1,C026,CUST-026,TXN-49071710,VIS-49320,SES-856597,order_completed,2026-07-12T13:57:00Z,...,NaN,CMP-002,NaN,TRK995853974,Delhivery,NaN,sara26@GMAIL.COM,NaN,mobile,Direct
2,ORD-1099,L1,1,CUST-013,CUST-013,txn-71743329,VIS-76062,SES-933292,purchase,09/01/2026 04:22 AM IST,...,NaN,NaN,NaN,TRK-12,DHL,delivered,li13@yahoo.com,964400,Tablet,Social
3,ORD-1114,2,2,CUST-922,NaN,txn-48368696,VIS-91393,SES-525850,payment_success,2026-03-14 21:44:00,...,NaN,NaN,NOT_AS_DESC,TRK219178680,NaN,Out for Delivery,priya922@yahoo.com,265579,Mobile,Email
4,ORD1211,L2,2,CUST071,CUST-071,txn-45138440,VIS-78060,SES-880356,cancel,1777967220,...,NaN,CMP-005,NaN,TRK764983105,DHL Express,NaN,amit71@GMAIL.COM,(404) 390-1551,desktop,email campaign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,ORD-1003,LINE-2,1,cust-031,CUST-031,TXN69302158,VIS-34957,SES-526833,cancel,2026-07-25T18:30:00Z,...,rejected,CMP-006,NaN,TRK967607278,FedEx,DELIVERED,amit31@gmail.com,+91-78147-35112,mobile,Social
612,ORD-1324,L2,3,CUST003,CUST-003,txn-14199629,VIS-77323,SES-166048,cancel,2026-06-09T12:00:00+05:30,...,rejected,CMP-003,late delivery,277496,BLUEDART,RTO,amit3@example.com,+91 8725754398,desktop,NaN
613,ORD-1271,L1,1,CUST-087,CUST-087,TXN-98773575,NaN,SES-184886,Purchase,1773487560,...,Expired,CMP-001,NaN,TRK844470084,Ecom Express,Out for Delivery,sara87@gmail.com,+91-88595-39075,Mobile,Direct
614,ORD-1031,L1,2,CUST-915,NaN,TXN-83571770,VIS-14946,SES-198867,cancel,07/20/2026 04:35 PM UTC,...,NaN,NaN,NaN,NaN,India Post,Delivered,sneha915@yahoo.com,(422) 951-2264,mobile,NaN
615,ORD1106,L1,1,cust-16,NaN,txn-99485713,VIS-86356,SES-787232,refund_request,2026-04-20T14:50:00+05:30,...,NaN,NaN,NaN,TRK693925686,Delhivery,DELIVERED,rahul16@yahoo.com,789173,unknown,Organic Search

In [917]:
df.to_csv('r-ecommerce_ raw_data.csv')
df

,Order_ID,Line_ID,Event_Version,Customer_ID,Master_Customer_ID,Transaction_ID,Visitor_ID,Session_ID,Event_Type,Order_TS,...,Promotion_Status,Campaign_ID,Return_Reason_Code,Tracking_ID,Carrier,Delivery_Status,Email,Phone_Number,Device,Acquisition_Channel
0,ORD-1098,L2,3,CUST-053,CUST-053,TXN-55514836,VIS-58611,NaN,payment_success,07/19/2026 02:45 PM PST,...,Applied,CMP-002,NaN,TRK279355399,fedex,Delivered,sara53@example.com,8016659593,mobile,organic
1,ORD-1082,L1,1,C026,CUST-026,TXN-49071710,VIS-49320,SES-856597,order_completed,2026-07-12T13:57:00Z,...,NaN,CMP-002,NaN,TRK995853974,Delhivery,NaN,sara26@GMAIL.COM,NaN,mobile,Direct
2,ORD-1099,L1,1,CUST-013,CUST-013,txn-71743329,VIS-76062,SES-933292,purchase,09/01/2026 04:22 AM IST,...,NaN,NaN,NaN,TRK-12,DHL,delivered,li13@yahoo.com,964400,Tablet,Social
3,ORD-1114,2,2,CUST-922,NaN,txn-48368696,VIS-91393,SES-525850,payment_success,2026-03-14 21:44:00,...,NaN,NaN,NOT_AS_DESC,TRK219178680,NaN,Out for Delivery,priya922@yahoo.com,265579,Mobile,Email
4,ORD1211,L2,2,CUST071,CUST-071,txn-45138440,VIS-78060,SES-880356,cancel,1777967220,...,NaN,CMP-005,NaN,TRK764983105,DHL Express,NaN,amit71@GMAIL.COM,(404) 390-1551,desktop,email campaign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
611,ORD-1003,LINE-2,1,cust-031,CUST-031,TXN69302158,VIS-34957,SES-526833,cancel,2026-07-25T18:30:00Z,...,rejected,CMP-006,NaN,TRK967607278,FedEx,DELIVERED,amit31@gmail.com,+91-78147-35112,mobile,Social
612,ORD-1324,L2,3,CUST003,CUST-003,txn-14199629,VIS-77323,SES-166048,cancel,2026-06-09T12:00:00+05:30,...,rejected,CMP-003,late delivery,277496,BLUEDART,RTO,amit3@example.com,+91 8725754398,desktop,NaN
613,ORD-1271,L1,1,CUST-087,CUST-087,TXN-98773575,NaN,SES-184886,Purchase,1773487560,...,Expired,CMP-001,NaN,TRK844470084,Ecom Express,Out for Delivery,sara87@gmail.com,+91-88595-39075,Mobile,Direct
614,ORD-1031,L1,2,CUST-915,NaN,TXN-83571770,VIS-14946,SES-198867,cancel,07/20/2026 04:35 PM UTC,...,NaN,NaN,NaN,NaN,India Post,Delivered,sneha915@yahoo.com,(422) 951-2264,mobile,NaN
615,ORD1106,L1,1,cust-16,NaN,txn-99485713,VIS-86356,SES-787232,refund_request,2026-04-20T14:50:00+05:30,...,NaN,NaN,NaN,TRK693925686,Delhivery,DELIVERED,rahul16@yahoo.com,789173,unknown,Organic Search

In [918]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 616 entries, 0 to 615
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order_ID              616 non-null    str
 1   Line_ID               595 non-null    object
 2   Event_Version         616 non-null    int64
 3   Customer_ID           601 non-null    str
 4   Master_Customer_ID    523 non-null    str
 5   Transaction_ID        581 non-null    str
 6   Visitor_ID            594 non-null    str
 7   Session_ID            592 non-null    str
 8   Event_Type            616 non-null    str
 9   Order_TS              616 non-null    str
 10  Event_TS              616 non-null    str
 11  Shipment_TS           568 non-null    str
 12  Delivery_TS           568 non-null    str
 13  Expected_Delivery_TS  616 non-null    str
 14  Product               616 non-null    str
 15  SKU                   616 non-null    str
 16  Product_Category      616 non-null    str
 17  Brand                 616 non-null    str
 18  Supplier_ID           602 non-null    str
 19  Inventory_ID          606 non-null    str
 20  Stock_Quantity        576 non-null    float64
 21  Qty                   613 non-null    object
 22  Unit                  560 non-null    str
 23  Unit_Price            608 non-null    object
 24  Discount              503 non-null    object
 25  Tax                   488 non-null    object
 26  Shipping_Cost         446 non-null    object
 27  Line_Total            616 non-null    float64
 28  Amount                616 non-null    object
 29  Refund_Amount         362 non-null    float64
 30  Currency              597 non-null    str
 31  Country               616 non-null    str
 32  State                 616 non-null    str
 33  Postal_Code           594 non-null    str
 34  Sales_Channel         605 non-null    str
 35  Payment_Method        616 non-null    str
 36  Payment_Status        616 non-null    str
 37  Status                616 non-null    str
 38  Promotion_Code        209 non-null    str
 39  Promotion_Status      180 non-null    str
 40  Campaign_ID           193 non-null    str
 41  Return_Reason_Code    69 non-null     str
 42  Tracking_ID           469 non-null    str
 43  Carrier               600 non-null    str
 44  Delivery_Status       573 non-null    str
 45  Email                 596 non-null    str
 46  Phone_Number          510 non-null    str
 47  Device                508 non-null    str
 48  Acquisition_Channel   540 non-null    str
dtypes: float64(3), int64(1), object(7), str(38)
memory usage: 235.9+ KB

In [919]:
df.head(10)

,Order_ID,Line_ID,Event_Version,Customer_ID,Master_Customer_ID,Transaction_ID,Visitor_ID,Session_ID,Event_Type,Order_TS,...,Promotion_Status,Campaign_ID,Return_Reason_Code,Tracking_ID,Carrier,Delivery_Status,Email,Phone_Number,Device,Acquisition_Channel
0,ORD-1098,L2,3,CUST-053,CUST-053,TXN-55514836,VIS-58611,NaN,payment_success,07/19/2026 02:45 PM PST,...,Applied,CMP-002,NaN,TRK279355399,fedex,Delivered,sara53@example.com,8016659593,mobile,organic
1,ORD-1082,L1,1,C026,CUST-026,TXN-49071710,VIS-49320,SES-856597,order_completed,2026-07-12T13:57:00Z,...,NaN,CMP-002,NaN,TRK995853974,Delhivery,NaN,sara26@GMAIL.COM,NaN,mobile,Direct
2,ORD-1099,L1,1,CUST-013,CUST-013,txn-71743329,VIS-76062,SES-933292,purchase,09/01/2026 04:22 AM IST,...,NaN,NaN,NaN,TRK-12,DHL,delivered,li13@yahoo.com,964400,Tablet,Social
3,ORD-1114,2,2,CUST-922,NaN,txn-48368696,VIS-91393,SES-525850,payment_success,2026-03-14 21:44:00,...,NaN,NaN,NOT_AS_DESC,TRK219178680,NaN,Out for Delivery,priya922@yahoo.com,265579,Mobile,Email
4,ORD1211,L2,2,CUST071,CUST-071,txn-45138440,VIS-78060,SES-880356,cancel,1777967220,...,NaN,CMP-005,NaN,TRK764983105,DHL Express,NaN,amit71@GMAIL.COM,(404) 390-1551,desktop,email campaign
5,ORD1163,L2,3,CUST-041,CUST-041,txn-37785216,VIS-10579,SES-350141,order_completed,2026-04-02T16:23:00+05:30,...,NaN,NaN,NaN,TRK915995939,Blue Dart,Delivered,li41@GMAIL.COM,(768) 932-3734,Desktop,Email
6,ORD-1282,L1,1,CUST-073,CUST-073,txn-60716325,VIS-33707,SES-790813,checkout_complete,2026-03-11T00:57:00+05:30,...,NaN,NaN,NaN,390716,BlueDart,delivered,rahul73@yahoo.com,NaN,DESKTOP,Referral
7,ORD1085,L2,2,CUST019,CUST-019,txn-42977091,VIS-11862,SES-696431,payment_failed,2026-09-13T06:49:00Z,...,NaN,NaN,NaN,TRK-12,FedEx,in_transit,mary19@example.com,8680671663,NaN,NaN
8,ORD-1094,L1,2,cust-905,NaN,txn-59711575,VIS-24973,SES-617453,checkout_complete,02 Jul 2026 02:14 GMT,...,Rejected,CMP-004,NaN,TRK-12,DHL Express,in_transit,john905@GMAIL.COM,+14931750818,Tablet,email campaign
9,ORD-1046,L1,2,CUST115,CUST-115,TXN-13994712,VIS-56562,SES-456855,order_completed,08/06/2026 07:07 AM PST,...,NaN,NaN,NaN,TRK213184291,fedex,Out for Delivery,li115@GMAIL.COM,739270,unknown,NaN

# **1.Trim whitespace and standardize order, customer, and transaction IDs; map aliases to master IDs**

Remove extra spaces from column names

In [920]:
df.columns = df.columns.str.strip()

Remove extra spaces from text values

In [921]:
for col in df.select_dtypes(include=["str"]).columns:
    df[col] = df[col].str.strip()

Standardize Order_ID

In [922]:
df["Order_ID"] = df["Order_ID"].str.upper()
df["Order_ID"] = df["Order_ID"].str.replace(" ", "", regex=False)
df["Order_ID"] = df["Order_ID"].str.replace("ORD--", "ORD-", regex=False)

df["Order_ID"] = df["Order_ID"].str.replace("ORD", "ORD-", regex=False)
df["Order_ID"] = df["Order_ID"].str.replace("ORD--", "ORD-", regex=False)

Standardize Customer_ID

In [923]:
df["Customer_ID"] = df["Customer_ID"].str.upper().str.strip()
df["Customer_ID"] = df["Customer_ID"].str.replace("CUST-", "", regex=False)
df["Customer_ID"] = df["Customer_ID"].str.replace("CUST", "", regex=False)
df["Customer_ID"] = df["Customer_ID"].str.replace("C", "", regex=False)
df["Customer_ID"] = "CUST-" + df["Customer_ID"]

Standardize Master_Customer_ID

In [924]:
df["Master_Customer_ID"] = df["Master_Customer_ID"].str.upper().str.strip()
df["Master_Customer_ID"] = df["Master_Customer_ID"].str.replace("CUST-", "", regex=False)
df["Master_Customer_ID"] = df["Master_Customer_ID"].str.replace("CUST", "", regex=False)
df["Master_Customer_ID"] = df["Master_Customer_ID"].str.replace("C", "", regex=False)
df["Master_Customer_ID"] = "CUST-" + df["Master_Customer_ID"]

 Map Customer_ID aliases to master IDs

In [925]:
df["Customer_ID"] = df["Master_Customer_ID"].combine_first(df["Customer_ID"])

Standardize Transaction_ID

In [926]:
df["Transaction_ID"] = df["Transaction_ID"].str.upper()
df["Transaction_ID"] = df["Transaction_ID"].str.replace(" ", "", regex=False)

In [927]:
print(df[["Order_ID","Customer_ID","Master_Customer_ID","Transaction_ID"]].head(10))

   Order_ID Customer_ID Master_Customer_ID Transaction_ID
0  ORD-1098    CUST-053           CUST-053   TXN-55514836
1  ORD-1082    CUST-026           CUST-026   TXN-49071710
2  ORD-1099    CUST-013           CUST-013   TXN-71743329
3  ORD-1114    CUST-922                NaN   TXN-48368696
4  ORD-1211    CUST-071           CUST-071   TXN-45138440
5  ORD-1163    CUST-041           CUST-041   TXN-37785216
6  ORD-1282    CUST-073           CUST-073   TXN-60716325
7  ORD-1085    CUST-019           CUST-019   TXN-42977091
8  ORD-1094    CUST-905                NaN   TXN-59711575
9  ORD-1046    CUST-115           CUST-115   TXN-13994712

# **2. Parse order and event timestamps and convert them to a common reporting timezone (UTC)**

Convert Order_TS to datetime in UTC

In [928]:
df["Order_TS"] = pd.to_datetime(df["Order_TS"], errors="coerce", utc=True, format="mixed")

Convert Event_TS to datetime in UTC

In [929]:
df["Event_TS"] = pd.to_datetime(df["Event_TS"], errors="coerce", utc=True, format="mixed")

In [930]:
print(df[["Order_TS", "Event_TS"]].head(10))

                   Order_TS                  Event_TS
0                       NaT 2026-07-19 09:21:00+00:00
1 2026-07-12 13:57:00+00:00 2026-07-12 14:40:00+00:00
2                       NaT                       NaT
3 2026-03-14 21:44:00+00:00 2026-03-14 22:04:00+00:00
4                       NaT 2026-05-05 09:11:00+00:00
5 2026-04-02 10:53:00+00:00                       NaT
6 2026-03-10 19:27:00+00:00 2026-03-11 01:27:00+00:00
7 2026-09-13 06:49:00+00:00                       NaT
8 2026-07-02 02:14:00+00:00 2026-02-07 03:15:00+00:00
9                       NaT 2026-08-06 07:26:00+00:00

# **3.Canonicalize product names, SKU codes, category labels, and brand names using the product catalogue.**

Canonicalize product names:
Remove extra spaces

In [931]:
df["Product"] = df["Product"].str.strip()

Correct product names

In [932]:
product_map = {"led desk lamp": "LED Desk Lamp",
    "LED Lamp (Desk)": "LED Desk Lamp",
    "Desk Lamp LED": "LED Desk Lamp",
    "yoga mat": "Yoga Mat",
    "YogaMat": "Yoga Mat",
    "Yoga Mat 6mm": "Yoga Mat",
    "Blk Ceramic Mug": "Black Ceramic Mug",
    "black ceramic mug": "Black Ceramic Mug",
    "Black Mug": "Black Ceramic Mug",
    "canvas tote": "Canvas Tote Bag",
    "Canvas Tote": "Canvas Tote Bag",
    "Tote - Canvas": "Canvas Tote Bag",
    "a5 notebook": "A5 Notebook",
    "A5 Note Book": "A5 Notebook",
    "Notebook A5": "A5 Notebook",
    "fitness watch": "Smart Fitness Watch",
    "Fitness Watch": "Smart Fitness Watch",
    "Fit Watch": "Smart Fitness Watch",
    "phone case x": "Phone Case X",
    "PhoneCase-X": "Phone Case X",
    "Phone Cover X": "Phone Case X",
    "slim jeans 32": "Slim Fit Jeans 32",
    "Slim Jeans 32": "Slim Fit Jeans 32",
    "Jeans Slim 32": "Slim Fit Jeans 32",
    "Run Shoes 9": "Running Shoes Size 9",
    "running shoes sz9": "Running Shoes Size 9",
    "Runner Shoe 9": "Running Shoes Size 9",
    "wireless earbud pro": "Wireless Earbuds Pro",
    "W. Earbuds Pro": "Wireless Earbuds Pro",
    "Earbuds Pro": "Wireless Earbuds Pro",
    "gel pen pack": "Gel Pen Pack",
    "Gel Pens": "Gel Pen Pack",
    "Gel Pen (Pack)": "Gel Pen Pack",
    "cotton tee l": "Cotton Tee L",
    "Cotton Tee (L)": "Cotton Tee L",
    "Cotton T-Shirt L": "Cotton Tee L",
    "cotton tee m": "Cotton Tee M",
    "Cotton Tee (M)": "Cotton Tee M",
    "Cotton T-Shirt M": "Cotton Tee M",
    "Cotton Socks 3-Pack": "Socks 3 Pack",
    "Cotton Socks (3pk)": "Socks 3 Pack",
    "cotton socks 3pk": "Socks 3 Pack",
    "Steel Water Bottle 1L": "Water Bottle Steel 1 L",
    "steel bottle 1l": "Water Bottle Steel 1 L",
    "SS Water Bottle 1L": "Water Bottle Steel 1 L"}

df["Product"] = df["Product"].replace(product_map)

Standardize SKU codes:

Remove spaces and convert to uppercase

In [933]:
df["SKU"] = df["SKU"].str.strip().str.upper()

Correct SKU codes

In [934]:
sku_map = {
    "YOGAMAT": "YOGA-MAT",
    "YOGA_MAT": "YOGA-MAT",
    "MUG-BLK": "MUG_BLK",
    "MUGBLK": "MUG_BLK",
    "PHONECASE-X": "PHONECASE_X",
    "PHONECASEX": "PHONECASE_X",
    "SOCKS-3PK": "SOCKS_3PK",
    "SOCKS3PK": "SOCKS_3PK",
    "BAG_01": "BAG-01",
    "BAG01": "BAG-01",
    "TSHIRT_L": "TSHIRT-L",
    "TSHIRTL": "TSHIRT-L",
    "TSHIRT_M": "TSHIRT-M",
    "TSHIRTM": "TSHIRT-M",
    "JEANS-32": "JEANS_32",
    "JEANS32": "JEANS_32",
    "WATCH_FIT": "WATCH-FIT",
    "WATCHFIT": "WATCH-FIT",
    "EARBUD_PRO": "EARBUD-PRO",
    "EARBUDPRO": "EARBUD-PRO",
    "LAMP-DESK": "LAMP_DESK",
    "LAMPDESK": "LAMP_DESK",
    "NOTEBOOK_A5": "NOTEBOOK-A5",
    "NOTEBOOKA5": "NOTEBOOK-A5",
    "PENGEL": "PEN-GEL",
    "PEN_GEL": "PEN-GEL",
    "BOTTLE_1L": "BOTTLE-1L",
    "BOTTLE1L": "BOTTLE-1L",
    "SHOE-RUN-9": "SHOE_RUN_9"
}

df["SKU"] = df["SKU"].replace(sku_map)

Standardize product categories

In [935]:
# Remove extra spaces
df["Product_Category"] = df["Product_Category"].str.strip()

# Standardize capitalization
df["Product_Category"] = df["Product_Category"].str.title()

# Correct category name
df["Product_Category"] = df["Product_Category"].str.replace("Home And Kitchen","Home & Kitchen",regex=False)

Standardize brand names:

In [936]:
# Remove extra spaces
df["Brand"] = df["Brand"].str.strip()

# Standardize capitalization
df["Brand"] = df["Brand"].str.title()

In [937]:
print(df[["Product", "SKU", "Product_Category", "Brand"]].head(20))

                 Product          SKU Product_Category       Brand
0               Yoga Mat     YOGA-MAT           Sports     Stridex
1          LED Desk Lamp    LAMP_DESK   Home & Kitchen  Brighthome
2      Black Ceramic Mug      MUG_BLK   Home & Kitchen    Homenest
3               Yoga Mat     YOGA-MAT           Sports     Stridex
4           Socks 3 Pack    SOCKS_3PK          Apparel   Urbanwear
5            A5 Notebook  NOTEBOOK-A5       Stationery   Paperplus
6        Canvas Tote Bag       BAG-01      Accessories     Carryco
7   Wireless Earbuds Pro   EARBUD-PRO      Electronics   Soundwave
8           Phone Case X  PHONECASE_X      Accessories     Carryco
9          LED Desk Lamp    LAMP_DESK   Home & Kitchen  Brighthome
10          Phone Case X  PHONECASE_X      Accessories     Carryco
11              Yoga Mat     YOGA-MAT           Sports     Stridex
12     Black Ceramic Mug      MUG_BLK   Home & Kitchen    Homenest
13       Canvas Tote Bag       BAG-01      Accessories     Carryco
14     Black Ceramic Mug      MUG_BLK   Home & Kitchen    Homenest
15          Phone Case X  PHONECASE_X      Accessories     Carryco
16          Cotton Tee L     TSHIRT-L          Apparel   Urbanwear
17          Socks 3 Pack    SOCKS_3PK          Apparel   Urbanwear
18       Canvas Tote Bag       BAG-01      Accessories     Carryco
19          Cotton Tee L     TSHIRT-L          Apparel   Urbanwear

Count unique values

In [938]:
print("Unique products:", df["Product"].nunique())
print("Unique SKUs:", df["SKU"].nunique())
print("Unique categories:", df["Product_Category"].nunique())
print("Unique brands:", df["Brand"].nunique())

Unique products: 15
Unique SKUs: 15
Unique categories: 7
Unique brands: 7

Check all distinct values

In [939]:
print("Products:", df["Product"].unique())
print("SKUs:", df["SKU"].unique())
print("Categories:", df["Product_Category"].unique())
print("Brands:", df["Brand"].unique())

Products: <StringArray>
[              'Yoga Mat',          'LED Desk Lamp',      'Black Ceramic Mug',
           'Socks 3 Pack',            'A5 Notebook',        'Canvas Tote Bag',
   'Wireless Earbuds Pro',           'Phone Case X',           'Cotton Tee L',
      'Slim Fit Jeans 32',    'Smart Fitness Watch',   'Running Shoes Size 9',
           'Cotton Tee M',           'Gel Pen Pack', 'Water Bottle Steel 1 L']
Length: 15, dtype: str
SKUs: <StringArray>
[   'YOGA-MAT',   'LAMP_DESK',     'MUG_BLK',   'SOCKS_3PK', 'NOTEBOOK-A5',
      'BAG-01',  'EARBUD-PRO', 'PHONECASE_X',    'TSHIRT-L',    'JEANS_32',
   'WATCH-FIT',  'SHOE_RUN_9',    'TSHIRT-M',     'PEN-GEL',   'BOTTLE-1L']
Length: 15, dtype: str
Categories: <StringArray>
[        'Sports', 'Home & Kitchen',        'Apparel',     'Stationery',
    'Accessories',    'Electronics',       'Footwear']
Length: 7, dtype: str
Brands: <StringArray>
[   'Stridex', 'Brighthome',   'Homenest',  'Urbanwear',  'Paperplus',
    'Carryco',  'Soundwave']
Length: 7, dtype: str

# **4.Normalize quantities and package units (each, pack, dozen) to the catalogue's base unit.**

In [940]:
df.columns.tolist()

['Order_ID',
 'Line_ID',
 'Event_Version',
 'Customer_ID',
 'Master_Customer_ID',
 'Transaction_ID',
 'Visitor_ID',
 'Session_ID',
 'Event_Type',
 'Order_TS',
 'Event_TS',
 'Shipment_TS',
 'Delivery_TS',
 'Expected_Delivery_TS',
 'Product',
 'SKU',
 'Product_Category',
 'Brand',
 'Supplier_ID',
 'Inventory_ID',
 'Stock_Quantity',
 'Qty',
 'Unit',
 'Unit_Price',
 'Discount',
 'Tax',
 'Shipping_Cost',
 'Line_Total',
 'Amount',
 'Refund_Amount',
 'Currency',
 'Country',
 'State',
 'Postal_Code',
 'Sales_Channel',
 'Payment_Method',
 'Payment_Status',
 'Status',
 'Promotion_Code',
 'Promotion_Status',
 'Campaign_ID',
 'Return_Reason_Code',
 'Tracking_ID',
 'Carrier',
 'Delivery_Status',
 'Email',
 'Phone_Number',
 'Device',
 'Acquisition_Channel']

Standardize unit names

In [941]:
df["Unit"] = df["Unit"].str.strip().str.lower()

df["Unit"] = df["Unit"].replace({"ea": "each","pcs": "each","pk": "pack","dz": "dozen"})

Convert Qty into numbers

In [942]:
df["Qty"] = pd.to_numeric(df["Qty"], errors="coerce")

Create a new column for normalized quantity

In [943]:
df["Normalized_Qty"] = df["Qty"]

Convert dozens into individual items

In [944]:
df.loc[df["Unit"] == "dozen", "Normalized_Qty"] = (df.loc[df["Unit"] == "dozen", "Qty"] * 12)

Create the normalized unit column

In [945]:
df["Normalized_Unit"] = df["Unit"]
df.loc[df["Unit"] == "dozen", "Normalized_Unit"] = "each"

In [946]:
print(df[["Product","SKU","Qty","Unit","Normalized_Qty","Normalized_Unit"]].head(20))

                 Product          SKU    Qty   Unit  Normalized_Qty  \
0               Yoga Mat     YOGA-MAT    1.0   pack             1.0
1          LED Desk Lamp    LAMP_DESK    1.0  dozen            12.0
2      Black Ceramic Mug      MUG_BLK    4.0  dozen            48.0
3               Yoga Mat     YOGA-MAT    4.0  dozen            48.0
4           Socks 3 Pack    SOCKS_3PK    2.0    NaN             2.0
5            A5 Notebook  NOTEBOOK-A5    1.0  dozen            12.0
6        Canvas Tote Bag       BAG-01    1.0  dozen            12.0
7   Wireless Earbuds Pro   EARBUD-PRO    1.0    NaN             1.0
8           Phone Case X  PHONECASE_X    2.0   pack             2.0
9          LED Desk Lamp    LAMP_DESK    2.0   each             2.0
10          Phone Case X  PHONECASE_X    3.0   each             3.0
11              Yoga Mat     YOGA-MAT    2.0   pack             2.0
12     Black Ceramic Mug      MUG_BLK  500.0  dozen          6000.0
13       Canvas Tote Bag       BAG-01    2.0  dozen            24.0
14     Black Ceramic Mug      MUG_BLK    2.0    NaN             2.0
15          Phone Case X  PHONECASE_X    1.0  dozen            12.0
16          Cotton Tee L     TSHIRT-L    2.0   each             2.0
17          Socks 3 Pack    SOCKS_3PK    5.0  dozen            60.0
18       Canvas Tote Bag       BAG-01    3.0   each             3.0
19          Cotton Tee L     TSHIRT-L    1.0    NaN             1.0

   Normalized_Unit
0             pack
1             each
2             each
3             each
4              NaN
5             each
6             each
7              NaN
8             pack
9             each
10            each
11            pack
12            each
13            each
14             NaN
15            each
16            each
17            each
18            each
19             NaN

# **5.Normalize prices, discounts, tax, shipping, and refunds to numeric decimal values; remove currency symbols**

the columns to clean

In [947]:
money_columns = ["Unit_Price","Discount","Tax","Shipping_Cost","Line_Total","Amount","Refund_Amount"]

Remove currency symbols and commas

In [948]:
for col in money_columns:
    df[col] = df[col].astype(str)
    df[col] = df[col].str.replace("₹", "", regex=False)
    df[col] = df[col].str.replace("$", "", regex=False)
    df[col] = df[col].str.replace("€", "", regex=False)
    df[col] = df[col].str.replace("£", "", regex=False)
    df[col] = df[col].str.replace(",", "", regex=False)
    df[col] = df[col].str.strip()

Convert values into numeric decimals

In [949]:
for col in money_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce").round(2)

In [950]:

print(df[money_columns].head(20))

    Unit_Price  Discount     Tax  Shipping_Cost  Line_Total   Amount  \
0         12.0       NaN    0.86            0.0       11.66    11.66
1         12.6     -50.0     NaN            0.0       13.61      NaN
2          9.0       0.0     NaN            7.5       38.88    38.88
3         10.8       0.0    3.46            NaN       46.66    46.66
4          NaN      69.8  113.08            NaN      741.28   741.28
5          NaN       0.0   27.00            0.0      177.00   177.00
6       1200.0       0.0  216.00          149.0     1416.00  1416.00
7         39.0       0.0     NaN            NaN       42.12      NaN
8          NaN       0.0     NaN            NaN      941.64      NaN
9         12.6       0.0     NaN            NaN       27.22    27.22
10         NaN       NaN     NaN            7.5       16.20      NaN
11       899.0       0.0     NaN          149.0     2121.64  2121.64
12         5.4       NaN    0.43            0.0        5.83     6.00
13         NaN       NaN  388.80           49.0     2548.80  2548.80
14       450.0       0.0  162.00            NaN     1062.00  1062.00
15         NaN       0.0    0.54            NaN        7.29     7.29
16         NaN       NaN  431.46            NaN     2828.46  2828.46
17         NaN       0.0    1.80            NaN       24.30    24.30
18      1200.0       0.0     NaN           49.0     4248.00  4248.00
19         NaN       NaN  115.06            0.0      754.26      NaN

    Refund_Amount
0            0.00
1             NaN
2             NaN
3           46.66
4             NaN
5            0.00
6            0.00
7             NaN
8            0.00
9             NaN
10            NaN
11            NaN
12           0.00
13           0.00
14            NaN
15            NaN
16        1414.23
17          24.30
18        2124.00
19           0.00

count te missing value of each column

In [951]:
print(df[money_columns].isnull().sum())

Unit_Price       262
Discount         196
Tax              172
Shipping_Cost    326
Line_Total         0
Amount           227
Refund_Amount    254
dtype: int64

to check the datatype

In [952]:
print(df[money_columns].dtypes)

Unit_Price       float64
Discount         float64
Tax              float64
Shipping_Cost    float64
Line_Total       float64
Amount           float64
Refund_Amount    float64
dtype: object

# **6. Standardize currencies and apply a documented daily FX rate for cross-currency reporting.**

In [953]:
print(df["Currency"].unique())
print(df["Currency"].value_counts(dropna=False))

<StringArray>
[ 'USD',    '€',  'US$',    '£',  'inr',   'Rs',  'INR',  'gbp',    '₹',
 'Euro',  'EUR',  'GBP',    '$',    nan,  'usd',  'eur']
Length: 16, dtype: str
Currency
INR     147
inr      75
₹        74
USD      58
Rs       56
GBP      39
US$      31
$        28
EUR      22
€        19
NaN      19
usd      13
£        11
gbp      10
Euro     10
eur       4
Name: count, dtype: int64

Convert currency labels to uppercase

In [954]:
df["Currency"] = df["Currency"].str.strip().str.upper()

Replace different currency formats with standard codes

In [955]:
df["Currency"] = df["Currency"].replace({
    "₹": "INR",
    "RS": "INR",
    "RS.": "INR",
    "US$": "USD",
    "$": "USD",
    "£": "GBP",
    "€": "EUR",
    "EURO": "EUR"})

print(df["Currency"].value_counts(dropna=False))

Currency
INR    352
USD    130
GBP     60
EUR     55
NaN     19
Name: count, dtype: int64

Convert order timestamp into date

In [956]:
df["Date"] = pd.to_datetime(
    df["Order_TS"], errors="coerce", utc=True
).dt.date

print(df[["Order_TS", "Date"]].head())

                   Order_TS        Date
0                       NaT         NaT
1 2026-07-12 13:57:00+00:00  2026-07-12
2                       NaT         NaT
3 2026-03-14 21:44:00+00:00  2026-03-14
4                       NaT         NaT

In [957]:

df["Amount"] = df["Amount"].astype(str).str.replace(",", "", regex=False)
df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")
print(df["Amount"].head())

0     11.66
1       NaN
2     38.88
3     46.66
4    741.28
Name: Amount, dtype: float64

In [958]:
rates = pd.DataFrame({
    "Date": [
        pd.to_datetime("2026-07-12").date(),
        pd.to_datetime("2026-07-12").date(),
        pd.to_datetime("2026-07-12").date(),
        pd.to_datetime("2026-07-12").date()
    ],
    "Currency": ["INR", "USD", "GBP", "EUR"],
    "Rate_INR": [1.0, 95.323, 126.6, 106]
})

print(rates.columns)
print(rates)

Index(['Date', 'Currency', 'Rate_INR'], dtype='str')
         Date Currency  Rate_INR
0  2026-07-12      INR     1.000
1  2026-07-12      USD    95.323
2  2026-07-12      GBP   126.600
3  2026-07-12      EUR   106.000

In [959]:
df = df.drop(
    columns=["Rate_INR", "Amount_INR"],
    errors="ignore"
)

df = df.merge(
    rates,
    on=["Date", "Currency"],
    how="left",
    validate="many_to_one"
)

print(df[["Date", "Currency", "Rate_INR"]].head(10))

         Date Currency  Rate_INR
0         NaT      USD       NaN
1  2026-07-12      EUR     106.0
2         NaT      USD       NaN
3  2026-03-14      GBP       NaN
4         NaT      INR       NaN
5  2026-04-02      INR       NaN
6  2026-03-10      INR       NaN
7  2026-09-13      USD       NaN
8  2026-07-02      INR       NaN
9         NaT      GBP       NaN

In [960]:
df["Amount_INR"] = (
    df["Amount"] * df["Rate_INR"]
).round(2)

print(df[[
    "Order_TS",
    "Currency",
    "Amount",
    "Rate_INR",
    "Amount_INR"
]].head(10))

                   Order_TS Currency   Amount  Rate_INR  Amount_INR
0                       NaT      USD    11.66       NaN         NaN
1 2026-07-12 13:57:00+00:00      EUR      NaN     106.0         NaN
2                       NaT      USD    38.88       NaN         NaN
3 2026-03-14 21:44:00+00:00      GBP    46.66       NaN         NaN
4                       NaT      INR   741.28       NaN         NaN
5 2026-04-02 10:53:00+00:00      INR   177.00       NaN         NaN
6 2026-03-10 19:27:00+00:00      INR  1416.00       NaN         NaN
7 2026-09-13 06:49:00+00:00      USD      NaN       NaN         NaN
8 2026-07-02 02:14:00+00:00      INR      NaN       NaN         NaN
9                       NaT      GBP    27.22       NaN         NaN

In [961]:
print("Missing dates:", df["Date"].isna().sum())
print("Missing rates:", df["Rate_INR"].isna().sum())
print("Missing converted amounts:", df["Amount_INR"].isna().sum())

print(df[df["Rate_INR"].isna()][["Date", "Currency"]].drop_duplicates())

Missing dates: 125
Missing rates: 612
Missing converted amounts: 615
           Date Currency
0           NaT      USD
3    2026-03-14      GBP
4           NaT      INR
5    2026-04-02      INR
6    2026-03-10      INR
..          ...      ...
587  2026-07-15      GBP
593  2026-08-31      EUR
600  2026-04-03      USD
603  2026-06-22      GBP
604  2026-04-27      EUR

[248 rows x 2 columns]

# 7. Normalize country, state, postal code, and sales-channel labels to approved values.

Remove extra spaces

In [962]:
df["Country"] = df["Country"].str.strip()
df["State"] = df["State"].str.strip()
df["Postal_Code"] = df["Postal_Code"].str.strip()
df["Sales_Channel"] = df["Sales_Channel"].str.strip()

Standardize Country and State names

In [963]:
df["Country"] = df["Country"].str.title()
df["State"] = df["State"].str.title()

 Standardize Postal Code

In [964]:
df["Postal_Code"] = df["Postal_Code"].astype("string")

Standardize Sales Channel

In [965]:
df["Sales_Channel"] = df["Sales_Channel"].str.lower()

df["Sales_Channel"] = df["Sales_Channel"].replace({
    "website": "online",
    "web": "online",
    "online store": "online",
    "physical store": "store",
    "retail store": "store"})

df["Sales_Channel"] = df["Sales_Channel"].str.title()

In [966]:
df["Country"].unique()
df["State"].unique()
df["Postal_Code"].unique()
df["Sales_Channel"].unique()

<StringArray>
[      'Store',  'Mobile_App',    'In-Store',         'App', 'Marketplace',
      'Online',           nan,  'Mobile App']
Length: 8, dtype: str

8. Detect duplicate order lines using order ID, line ID, SKU, and event version; retain the authoritative record.

 Sort by Event_Version

In [967]:
df = df.sort_values("Event_Version")

 Remove duplicates and keep the latest version

In [968]:
df = df.drop_duplicates(subset=["Order_ID", "Line_ID", "SKU"],keep="last")

9. Validate quantity, unit price, discount, tax, and line-total ranges; flag impossible or negative values for review.

 Check for negative or impossible values

In [969]:
df["Review_Flag"] = (
    (df["Qty"] <= 0) |
    (df["Unit_Price"] < 0) |
    (df["Discount"] < 0) |
    (df["Tax"] < 0) |
    (df["Line_Total"] < 0) |
    (df["Discount"] > df["Unit_Price"]))

print(df[df["Review_Flag"]])
print("Rows needing review:", df["Review_Flag"].sum())

     Order_ID Line_ID  Event_Version Customer_ID Master_Customer_ID  \
599  ORD-1330      L2              1    CUST-013           CUST-013
592  ORD-1228      L1              1    CUST-037           CUST-037
59   ORD-1169  LINE-1              1    CUST-013           CUST-013
499  ORD-1096      L2              1    CUST-120           CUST-120
498  ORD-1151      L1              1    CUST-054           CUST-054
489  ORD-1084      L1              1    CUST-079           CUST-079
486  ORD-1294      L2              1    CUST-070           CUST-070
430  ORD-1189      L2              1    CUST-014           CUST-014
222  ORD-1293      L1              1    CUST-108           CUST-108
212  ORD-1057      L1              1    CUST-015           CUST-015
410  ORD-1139      L2              1    CUST-022                NaN
267  ORD-1144      L1              1    CUST-098                NaN
252  ORD-1292      L2              1    CUST-093           CUST-093
280  ORD-1082      L1              1    CUST-026           CUST-026
399  ORD-1048  LINE-1              1    CUST-008           CUST-008
315  ORD-1162      L1              1    CUST-054           CUST-054
358  ORD-1307      L2              1    CUST-015           CUST-015
355  ORD-1321      L1              1    CUST-098           CUST-098
353  ORD-1334      L1              1    CUST-025           CUST-025
349  ORD-1089      L2              1    CUST-053           CUST-053
368  ORD-1082      L3              1    CUST-026           CUST-026
366  ORD-1281      L1              1    CUST-098           CUST-098
485  ORD-1201      L1              1    CUST-109           CUST-109
480  ORD-1123       1              1    CUST-061           CUST-061
377  ORD-1337      L3              2    CUST-059           CUST-059
398  ORD-1303      L1              2    CUST-109           CUST-109
271  ORD-1248      L1              2    CUST-062           CUST-062
441  ORD-1133      L1              2    CUST-077           CUST-077
488  ORD-1103      L2              2    CUST-077           CUST-077
139  ORD-1222      L1              2    CUST-046           CUST-046
465  ORD-1110      L1              2    CUST-034           CUST-034
612  ORD-1324      L2              3    CUST-003           CUST-003
434  ORD-1220      L1              3    CUST-029           CUST-029
380  ORD-1233      L1              3    CUST-033           CUST-033
547  ORD-1108      L2              3    CUST-069           CUST-069
558  ORD-1088      L1              3    CUST-051           CUST-051
43   ORD-1111      L1              3    CUST-009           CUST-009

    Transaction_ID Visitor_ID  Session_ID         Event_Type  \
599   TXN-20418550  VIS-78937  SES-589688           Purchase
592   TXN-46643560  VIS-47918  SES-353052           Purchase
59    TXN-59193931  VIS-24970  SES-662533             cancel
499    TXN84137409  VIS-69151  SES-218877    payment_success
498    TXN93794171  VIS-96140  SES-324014           purchase
489   TXN-35433791  VIS-87000  SES-422038           purchase
486   TXN-60796271  VIS-80865  SES-400050    order_completed
430   TXN-50437758  VIS-41108  SES-852193             cancel
222    TXN86456040  VIS-31792  SES-212527     refund_request
212    TXN75641573  VIS-92729  SES-102342     refund_request
410   TXN-96844604  VIS-66151  SES-462126     payment_failed
267   TXN-29496391  VIS-31013  SES-512778    order_completed
252   TXN-61269135  VIS-66644  SES-689776     refund_request
280   TXN-49071710  VIS-49320  SES-856597    order_completed
399    TXN88538733  VIS-59219  SES-370463    payment_success
315   TXN-36905453  VIS-67783  SES-743709           Purchase
358   TXN-85696454  VIS-81668  SES-687823    order_completed
355   TXN-73696929  VIS-28788  SES-472939    order_completed
353   TXN-68084777  VIS-84351         NaN     payment_failed
349   TXN-14075870  VIS-21727  SES-674721    order_completed
368   TXN-30805333  VIS-49320  SES-856597           purchase
366    TXN79044275  VIS-32155  SES-262201             cancel
485   TXN-55014479  VIS-29947  SES-244354     payment_failed
480   TXN-25119992  VIS-28580  SES-187781             cancel
377            NaN  VIS-21944  SES-405094           Purchase
398   TXN-41310102  VIS-56340  SES-945822     refund_request
271    TXN82748700  VIS-40207  SES-678084    payment_success
441   TXN-49386435  VIS-50901  SES-371108    order_completed
488            NaN  VIS-63955  SES-900028           Purchase
139   TXN-23979159  VIS-44674  SES-509488    order_completed
465   TXN-32328144  VIS-72747  SES-896626  checkout_complete
612   TXN-14199629  VIS-77323  SES-166048             cancel
434    TXN82215395  VIS-42502  SES-141995           Purchase
380   TXN-18063521  VIS-36946  SES-423526    payment_success
547   TXN-25026574  VIS-10716  SES-688521    payment_success
558    TXN94917104  VIS-34896  SES-338801  checkout_complete
43     TXN84725325  VIS-79695  SES-965968  checkout_complete

                     Order_TS  ...                Email     Phone_Number  \
599 2026-09-19 16:31:00+00:00  ...    kavya13@GMAIL.COM           730840
592 2026-07-20 21:19:00+00:00  ...    arjun37@GMAIL.COM   (952) 405-6454
59  2026-11-05 15:07:00+00:00  ...   amit13@example.com     +15841375879
499 2026-04-01 00:15:00+00:00  ...  sara120@outlook.com           750475
498                       NaT  ...       li54@gmail.com     +14418609598
489 2026-08-25 20:03:00+00:00  ...         not-an-email     +18545463326
486 2026-07-05 17:49:00+00:00  ...     john70@GMAIL.COM           834178
430                       NaT  ...     li14@example.com       7648176855
222 2026-08-24 11:15:00+00:00  ...   sneha108@gmail.com   (294) 302-3187
212 2026-03-31 03:49:00+00:00  ...       li15@gmail.com   +91 9924590969
410 2026-05-08 02:49:00+00:00  ...   sara22@outlook.com           496886
267                       NaT  ...     mary98@GMAIL.COM   (875) 655-9751
252 2026-04-19 19:13:00+00:00  ...     li93@outlook.com       9971370655
280 2026-07-12 20:57:00+00:00  ...     sara26@GMAIL.COM              NaN
399 2026-05-16 19:06:00+00:00  ...      sara8@GMAIL.COM   (262) 525-8615
315 2026-04-15 19:14:00+00:00  ...    rahul54@gmail.com  +91-98464-96080
358 2026-04-15 05:57:00+00:00  ...   amit15@outlook.com              NaN
355 2026-10-03 14:24:00+00:00  ...  kavya98@example.com  +91-83293-56960
353 2026-03-14 08:44:00+00:00  ...     li25@outlook.com       8038575732
349 2026-07-13 08:11:00+00:00  ...                  NaN           260044
368 2026-07-12 08:27:00+00:00  ...     sara26@GMAIL.COM              NaN
366 2026-05-13 10:07:00+00:00  ...     sara98@GMAIL.COM   (658) 276-7161
485 2026-03-01 20:35:00+00:00  ...   arjun109@GMAIL.COM       9965526924
480                       NaT  ...    rahul61@yahoo.com           431145
377 2026-03-23 08:41:00+00:00  ...  sneha59@example.com   +91 8017316472
398                       NaT  ...  john109@outlook.com              NaN
271                       NaT  ...                  NaN           297540
441 2026-06-20 10:14:00+00:00  ...  kavya77@example.com  +91-82544-13296
488 2026-03-15 22:28:00+00:00  ...  kavya77@example.com              NaN
139 2026-07-02 08:18:00+00:00  ...     amit46@gmail.com              NaN
465                       NaT  ...     mary34@yahoo.com  +91-80150-26766
612 2026-06-09 06:30:00+00:00  ...    amit3@example.com   +91 8725754398
434 2026-07-27 21:25:00+00:00  ...     mary29@GMAIL.COM       7455451518
380                       NaT  ...    arjun33@gmail.com  +91-73743-13471
547 2026-06-18 13:46:00+00:00  ...   john69@example.com           833455
558 2026-04-10 13:53:00+00:00  ...    kavya51@gmail.com           618239
43                        NaT  ...   sneha9@example.com   +91 8810324044

      Device Acquisition_Channel Normalized_Qty Normalized_Unit        Date  \
599   Mobile                 NaN           12.0            each  2026-09-19
592  unknown              direct          -12.0            each  2026-07-20
59    Mobile               Email           12.0            each  2026-11-05
499  Desktop         Paid Search            5.0            each  2026-04-01
498   mobile            Referral            0.0            each         NaT
489   mobile          Google Ads           12.0            each  2026-08-25
486  DESKTOP      email campaign           -1.0            pack  2026-07-05
430      NaN              direct            1.0            pack         NaT
222  Desktop      email campaign            1.0            pack  2026-08-24
212  Desktop          Google Ads          -12.0            each  2026-03-31
410   Mobile              Social            0.0            each  2026-05-08
267   mobile               Email            2.0            each         NaT
252  unknown                 NaN           -3.0            pack  2026-04-19
280   mobile              Direct           12.0            each  2026-07-12
399   mobile            Referral            1.0             NaN  2026-05-16
315  DESKTOP              Social            0.0            each  2026-04-15
358  desktop                 NaN           -1.0            each  2026-04-15
355   Tablet      email campaign            0.0            each  2026-10-03
353  desktop         Paid Search            1.0            each  2026-03-14
349  desktop          Google Ads            1.0            each  2026-07-13
368  Desktop      email campaign           -5.0            pack  2026-07-12
366  desktop             organic            2.0            each  2026-05-13
485      NaN                 NaN            0.0            pack  2026-03-01
480      NaN              Direct          500.0            each         NaT
377      NaN               Email            2.0            pack  2026-03-23
398      NaN      email campaign          -12.0            each         NaT
271      NaN              Direct            2.0            each         NaT
441   Tablet              direct            5.0            each  2026-06-20
488   Tablet          Google Ads           12.0            each  2026-03-15
139   mobile           Instagram            0.0            each  2026-07-02
465  unknown                 NaN            4.0            each         NaT
612  desktop                 NaN            2.0            each  2026-06-09
434  unknown                 NaN           12.0            each  2026-07-27
380      NaN                 NaN            1.0            pack         NaT
547   mobile               Email            0.0            each  2026-06-18
558  desktop              direct            2.0            pack  2026-04-10
43    Mobile            Referral            2.0            each         NaT

    Rate_INR Amount_INR Review_Flag
599      NaN        NaN        True
592      NaN        NaN        True
59       NaN        NaN        True
499      NaN        NaN        True
498      NaN        NaN        True
489      NaN        NaN        True
486      NaN        NaN        True
430      NaN        NaN        True
222      NaN        NaN        True
212      NaN        NaN        True
410      NaN        NaN        True
267      NaN        NaN        True
252      NaN        NaN        True
280    106.0        NaN        True
399      NaN        NaN        True
315      NaN        NaN        True
358      NaN        NaN        True
355      NaN        NaN        True
353      NaN        NaN        True
349      NaN        NaN        True
368    106.0        NaN        True
366      NaN        NaN        True
485      NaN        NaN        True
480      NaN        NaN        True
377      NaN        NaN        True
398      NaN        NaN        True
271      NaN        NaN        True
441      NaN        NaN        True
488      NaN        NaN        True
139      NaN        NaN        True
465      NaN        NaN        True
612      NaN        NaN        True
434      NaN        NaN        True
380      NaN        NaN        True
547      NaN        NaN        True
558      NaN        NaN        True
43       NaN        NaN        True

[37 rows x 55 columns]
Rows needing review: 37

In [970]:
df.tail()

,Order_ID,Line_ID,Event_Version,Customer_ID,Master_Customer_ID,Transaction_ID,Visitor_ID,Session_ID,Event_Type,Order_TS,...,Email,Phone_Number,Device,Acquisition_Channel,Normalized_Qty,Normalized_Unit,Date,Rate_INR,Amount_INR,Review_Flag
583,ORD-1081,L1,3,CUST-040,CUST-040,TXN53335744,VIS-46007,SES-116619,payment_failed,2026-08-26 21:11:00+00:00,...,NaN,535029,Mobile,Paid Search,2.0,pack,2026-08-26,NaN,NaN,False
525,ORD-1285,L1,4,CUST-020,CUST-020,TXN-51142480,VIS-24033,SES-901856,cancel,2026-03-31 00:09:00+00:00,...,sneha20@yahoo.com,690136,mobile,NaN,1.0,NaN,2026-03-31,NaN,NaN,False
258,ORD-1269,L1,4,CUST-060,CUST-060,TXN-63226396,VIS-86545,SES-721814,Purchase,2026-08-21 18:06:00+00:00,...,arjun60@GMAIL.COM,524678,Tablet,Social,1.0,each,2026-08-21,NaN,NaN,False
180,ORD-1225,L2,4,CUST-036,CUST-036,TXN-14657496,VIS-50484,SES-611915,refund_request,2026-09-17 08:46:00+00:00,...,priya36@example.com,+91 9983270087,mobile,NaN,1.0,pack,2026-09-17,NaN,NaN,False
579,ORD-1259,LINE-1,4,CUST-050,CUST-050,TXN20892215,VIS-25331,SES-342328,payment_success,2026-09-07 08:08:00+00:00,...,user@@mail.com,450695,desktop,Instagram,3.0,NaN,2026-09-07,NaN,NaN,False

10. Normalize payment method and payment status values (e.g., card, wallet; captured, pending, failed).

 Remove extra spaces

In [971]:
df["Payment_Method"] = df["Payment_Method"].str.strip()
df["Payment_Status"] = df["Payment_Status"].str.strip()

Convert values to lowercase

In [972]:
df["Payment_Method"] = df["Payment_Method"].str.lower()
df["Payment_Status"] = df["Payment_Status"].str.lower()

payment methods

In [973]:
df["Payment_Method"] = df["Payment_Method"].replace({
    "credit card": "card",
    "debit card": "card",
    "e-wallet": "wallet",
    "digital wallet": "wallet"
})

payment statuses

In [974]:
df["Payment_Status"] = df["Payment_Status"].replace({
    "complete": "captured",
    "completed": "captured",
    "success": "captured",
    "successful": "captured",
    "in progress": "pending",
    "unsuccessful": "failed"
})

In [975]:
df["Payment_Method"].value_counts(dropna=False)
df["Payment_Status"].value_counts(dropna=False)

Payment_Status
captured      169
failed        102
pending       101
refunded       63
paid           44
auth           42
authorized     33
Name: count, dtype: int64

# 11. Match customer records using the approved customer master; keep unmatched IDs in an exception queue.

Create a customer master from your current data

In [976]:
customer_master = df[["Customer_ID"]].drop_duplicates()

Get approved customer IDs

In [977]:
approved_ids = customer_master["Customer_ID"].dropna().unique()

Find unmatched customer IDs

In [978]:
exceptions = df[~df["Customer_ID"].isin(approved_ids)]

In [979]:
print("Unmatched records:", len(exceptions))
print(exceptions[["Customer_ID"]])

Unmatched records: 2
    Customer_ID
311         NaN
566         NaN

# 12. Normalize promotion codes and distinguish applied, expired, and rejected promotions.

In [980]:
df["Promotion_Code"] = df["Promotion_Code"].str.strip().str.upper()
df["Promotion_Status"] = df["Promotion_Status"].str.strip().str.lower()

In [981]:
df["Promotion_Status"] = df["Promotion_Status"].replace({
    "success": "applied",
    "successful": "applied",
    "used": "applied",
    "invalid": "rejected",
    "declined": "rejected",
    "out of date": "expired"
})

In [982]:
df["Promotion_Code"].value_counts(dropna=False)
df["Promotion_Status"].value_counts(dropna=False)

Promotion_Status
NaN         390
rejected     68
expired      49
applied      47
Name: count, dtype: int64

# 13. Standardize return/refund reason codes and link returns to the original order line.

In [983]:
df["Return_Reason_Code"] = df["Return_Reason_Code"].str.strip().str.upper()
df["Return_Reason_Code"] = df["Return_Reason_Code"].replace({
    "WRONG ITEM": "WRONG_ITEM",
    "DAMAGED ITEM": "DAMAGED_ITEM",
    "LATE DELIVERY": "LATE_DELIVERY",
    "NOT AS DESCRIBED": "NOT_AS_DESCRIBED",
    "DEFECTIVE PRODUCT": "DEFECTIVE_PRODUCT"
})

# 3. Check the cleaned reason codes
df["Return_Reason_Code"].value_counts(dropna=False)

Return_Reason_Code
NaN                 489
NOT_AS_DESC           7
DAMAGED               7
SIZE ISSUE            7
DMG                   6
NOT_AS_DESCRIBED      6
LATE                  6
WRONG_ITEM            5
LATE_DELIVERY         5
DAMAGED_ITEM          4
OTHER                 4
CHANGED MIND          3
CHG_MIND              3
SIZE                  2
Name: count, dtype: int64

In [984]:
returns = df[df["Return_Reason_Code"].notna()]
print(returns[["Order_ID", "Line_ID", "Return_Reason_Code", "Refund_Amount"]])

     Order_ID Line_ID Return_Reason_Code  Refund_Amount
20   ORD-1250      L2         WRONG_ITEM       12100.08
18   ORD-1325      L1      LATE_DELIVERY        2124.00
17   ORD-1126      L1               SIZE          24.30
16   ORD-1143      L2                DMG        1414.23
35   ORD-1175      L2   NOT_AS_DESCRIBED           5.83
..        ...     ...                ...            ...
513  ORD-1088      L2           CHG_MIND         565.69
511  ORD-1021      L1         WRONG_ITEM        1416.00
201  ORD-1025      L1      LATE_DELIVERY          11.66
121  ORD-1142      L1         SIZE ISSUE          12.96
89   ORD-1097      L1       CHANGED MIND           2.62

[65 rows x 4 columns]

In [985]:
print(df.columns.tolist())

['Order_ID', 'Line_ID', 'Event_Version', 'Customer_ID', 'Master_Customer_ID', 'Transaction_ID', 'Visitor_ID', 'Session_ID', 'Event_Type', 'Order_TS', 'Event_TS', 'Shipment_TS', 'Delivery_TS', 'Expected_Delivery_TS', 'Product', 'SKU', 'Product_Category', 'Brand', 'Supplier_ID', 'Inventory_ID', 'Stock_Quantity', 'Qty', 'Unit', 'Unit_Price', 'Discount', 'Tax', 'Shipping_Cost', 'Line_Total', 'Amount', 'Refund_Amount', 'Currency', 'Country', 'State', 'Postal_Code', 'Sales_Channel', 'Payment_Method', 'Payment_Status', 'Status', 'Promotion_Code', 'Promotion_Status', 'Campaign_ID', 'Return_Reason_Code', 'Tracking_ID', 'Carrier', 'Delivery_Status', 'Email', 'Phone_Number', 'Device', 'Acquisition_Channel', 'Normalized_Qty', 'Normalized_Unit', 'Date', 'Rate_INR', 'Amount_INR', 'Review_Flag']

# 14. Validate shipment tracking IDs and normalize carrier names and delivery statuses.

Remove extra spaces

In [986]:
df["Tracking_ID"] = df["Tracking_ID"].str.strip()
df["Carrier"] = df["Carrier"].str.strip()
df["Delivery_Status"] = df["Delivery_Status"].str.strip()

Normalize carrier names

In [987]:
df["Carrier"] = df["Carrier"].str.title()

df["Carrier"] = df["Carrier"].replace({
    "Dhl Express": "DHL",
    "Fedex": "FedEx",
    "Ups": "UPS",
    "Usps": "USPS"
})

 Normalize delivery statuses

In [988]:
df["Delivery_Status"] = df["Delivery_Status"].str.lower()

df["Delivery_Status"] = df["Delivery_Status"].replace({
    "in transit": "shipped",
    "on the way": "shipped",
    "delivered successfully": "delivered",
    "delivery complete": "delivered",
    "not delivered": "failed"
})

In [989]:
df["Tracking_Review"] = df["Tracking_ID"].isna() | (df["Tracking_ID"] == "")

In [990]:
df[["Tracking_ID", "Carrier", "Delivery_Status", "Tracking_Review"]].head(10)

print("Missing tracking IDs:", df["Tracking_Review"].sum())
print(df["Carrier"].value_counts(dropna=False))
print(df["Delivery_Status"].value_counts(dropna=False))

Missing tracking IDs: 135
Carrier
Bluedart        104
Delhivery        87
FedEx            71
Dhl              62
DHL              55
Ecom Express     46
India Post       41
Blue Dart        39
Ecom Exp         36
NaN              13
Name: count, dtype: int64
Delivery_Status
delivered             320
NaN                    39
out for delivery       36
in_transit             34
pending                34
ofd                    29
shipped                26
rto                    17
failed attempt         11
returned to origin      8
Name: count, dtype: int64

# 15. Mask email addresses and phone numbers in analyst-facing extracts.

 Mask email addresses

In [991]:
df["Email"] = df["Email"].str.replace(
    r"(^.).*(@.*$)", r"\1***\2", regex=True
)

Mask phone numbers

In [992]:
df["Phone_Number"] = df["Phone_Number"].astype("string").str.replace(
    r"\d(?=\d{4})", "*", regex=True
)

In [993]:
df[["Email", "Phone_Number"]].head(10)

                Email     Phone_Number
603    k***@gmail.com           **0943
601  k***@example.com     +*******6012
600    j***@gmail.com       ******8213
599    k***@GMAIL.COM           **0840
598  r***@outlook.com           **1688
21   s***@example.com   (893) 602-3096
20   l***@example.com   +91 ******7243
18   a***@outlook.com  +91-*9487-*6789
17     a***@gmail.com  +91-*9116-*6105
16   r***@outlook.com   +91 ******1406

Create a separate copy for analysts

In [994]:

analyst_df = df.copy()

analyst_df["Email"] = analyst_df["Email"].str.replace(
    r"(^.).*(@.*$)", r"\1***\2", regex=True
)

analyst_df["Phone_Number"] = analyst_df["Phone_Number"].astype("string").str.replace(
    r"\d(?=\d{4})", "*", regex=True
)

# 16. Identify suspicious order spikes, repeated failed payments, or unusually high refund ratios for review.

Find orders with unusually high amounts

In [995]:

average_amount = df["Amount"].mean()
limit = average_amount * 3

high_orders = df[df["Amount"] > limit]

print("Orders with unusually high amounts:")
print(high_orders[["Order_ID", "Amount"]])

Orders with unusually high amounts:
     Order_ID    Amount
20   ORD-1250   6050.04
26   ORD-1217  10616.46
468  ORD-1161   6050.04
111  ORD-1113  10748.15
107  ORD-1304  49545.84
517  ORD-1158   7078.00
505  ORD-1313  10616.46
305  ORD-1049  15130.14
316  ORD-1244   7078.00
330  ORD-1304  14146.00
327  ORD-1307  10618.00
607  ORD-1291  63705.84
348  ORD-1253  12093.35
194  ORD-1014  49545.84
452  ORD-1129   6364.03
156  ORD-1043  11313.84
130  ORD-1063  15926.46
503  ORD-1267  14146.00
292  ORD-1145  60159.94
226  ORD-1218   6050.04
192  ORD-1103  14155.28

In [996]:

failed = df[df["Payment_Status"].str.lower() == "failed"]

failed_count = failed.groupby("Customer_ID")["Order_ID"].count()


suspicious_customers = failed_count[failed_count >= 3]

print("Customers with repeated failed payments:")
print(suspicious_customers)

Customers with repeated failed payments:
Customer_ID
CUST-002    3
CUST-006    3
CUST-022    3
CUST-028    3
CUST-032    4
CUST-045    3
CUST-061    3
CUST-064    4
CUST-066    3
CUST-077    9
CUST-098    7
CUST-103    3
CUST-110    3
CUST-111    3
CUST-904    3
CUST-924    3
Name: Order_ID, dtype: int64

In [997]:

df["Amount"] = pd.to_numeric(df["Amount"], errors="coerce")
df["Refund_Amount"] = pd.to_numeric(df["Refund_Amount"], errors="coerce")

df["Refund_Ratio"] = df["Refund_Amount"] / df["Amount"]

high_refunds = df[df["Refund_Ratio"] > 0.5]

print("Orders with high refund ratios:")
print(high_refunds[["Order_ID", "Amount", "Refund_Amount", "Refund_Ratio"]])

Orders with high refund ratios:
     Order_ID   Amount  Refund_Amount  Refund_Ratio
20   ORD-1250  6050.04       12100.08      2.000000
17   ORD-1126    24.30          24.30      1.000000
35   ORD-1175     5.83           5.83      1.000000
55   ORD-1061  1593.00        1593.00      1.000000
77   ORD-1202    34.99          34.99      1.000000
94   ORD-1068   700.09         350.05      0.500007
81   ORD-1230     2.16           2.16      1.000000
573  ORD-1143   941.64         941.64      1.000000
106  ORD-1337   141.60         212.40      1.500000
177  ORD-1007    46.66          46.66      1.000000
415  ORD-1114     1.94           1.94      1.000000
396  ORD-1324    15.55          15.55      1.000000
391  ORD-1130     4.86           4.86      1.000000
336  ORD-1175    11.66          11.66      1.000000
608  ORD-1328  3538.82        7077.64      2.000000
22   ORD-1202    38.00          37.91      0.997632
220  ORD-1250   127.44         127.44      1.000000
218  ORD-1126    30.33          30.33      1.000000
452  ORD-1129  6364.03       12728.06      2.000000
441  ORD-1133  3643.25        3643.25      1.000000
54   ORD-1280     2.00           1.94      0.970000
593  ORD-1202    58.32          58.32      1.000000
3    ORD-1114    46.66          46.66      1.000000
511  ORD-1021  1416.00        1416.00      1.000000
201  ORD-1025    11.66          11.66      1.000000

# 17. Validate product category, supplier, and inventory keys against reference tables.

Create reference tables from unique values

In [998]:
category_master = df["Product_Category"].dropna().unique()
supplier_master = df["Supplier_ID"].dropna().unique()
inventory_master = df["Inventory_ID"].dropna().unique()

In [999]:
df["Category_Review"] = ~df["Product_Category"].isin(category_master)
df["Supplier_Review"] = ~df["Supplier_ID"].isin(supplier_master)
df["Inventory_Review"] = ~df["Inventory_ID"].isin(inventory_master)

# 5. Display results
df[[
    "Product_Category", "Supplier_ID", "Inventory_ID",
    "Category_Review", "Supplier_Review", "Inventory_Review"
]].head(10)

,Product_Category,Supplier_ID,Inventory_ID,Category_Review,Supplier_Review,Inventory_Review
603,Apparel,SUP-102,INV-5002,False,False,False
601,Electronics,SUP-105,INV-5013,False,False,False
600,Apparel,SUP-102,INV-5002,False,False,False
599,Stationery,SUP-106,INV-5010,False,False,False
598,Footwear,SUP-104,INV-5005,False,False,False
21,Electronics,SUP-105,INV-5013,False,False,False
20,Apparel,SUP-102,INV-5011,False,False,False
18,Accessories,SUP-103,INV-5004,False,False,False
17,Apparel,SUP-102,INV-5014,False,False,False
16,Apparel,SUP-102,INV-5003,False,False,False

# 18. Separate cancelled, test, and fraud-review orders from fulfilled revenue using explicit rules.

Convert status values to lowercase

In [1000]:

df["Status"] = df["Status"].str.strip().str.lower()
df["Event_Type"] = df["Event_Type"].str.strip().str.lower()

Identify cancelled orders

In [1001]:
cancelled = df[df["Status"].str.contains("cancel", na=False)]

Identify test orders

In [1002]:
test_orders = df[
    df["Status"].str.contains("test", na=False) |
    df["Event_Type"].str.contains("test", na=False)]

Identify fraud-review orders

In [1003]:
fraud_review = df[df["Status"].str.contains("fraud", na=False)]

 Keep fulfilled orders separate

In [1004]:
fulfilled = df[
    df["Status"].str.contains("deliver|fulfill|complete", na=False) &
    ~df["Status"].str.contains("cancel|test|fraud", na=False) &
    ~df["Event_Type"].str.contains("test", na=False)]

 Calculate fulfilled revenue

In [1005]:
fulfilled_revenue = fulfilled["Line_Total"].sum()

Display results

In [1006]:
print("Cancelled orders:", len(cancelled))
print("Test orders:", len(test_orders))
print("Fraud-review orders:", len(fraud_review))
print("Fulfilled orders:", len(fulfilled))
print("Fulfilled revenue:", fulfilled_revenue)

Cancelled orders: 44
Test orders: 27
Fraud-review orders: 36
Fulfilled orders: 283
Fulfilled revenue: 532728.8200000001

# 19. Handle missing values with documented rules; do not replace unknown discounts or customer IDs with arbitrary values.

Check missing values

In [1007]:
print(df.isnull().sum())

Order_ID                  0
Line_ID                  19
Event_Version             0
Customer_ID               2
Master_Customer_ID       84
Transaction_ID           33
Visitor_ID               21
Session_ID               22
Event_Type                0
Order_TS                114
Event_TS                120
Shipment_TS              44
Delivery_TS              44
Expected_Delivery_TS      0
Product                   0
SKU                       0
Product_Category          0
Brand                     0
Supplier_ID              10
Inventory_ID              9
Stock_Quantity           36
Qty                       6
Unit                     50
Unit_Price              232
Discount                177
Tax                     148
Shipping_Cost           293
Line_Total                0
Amount                  203
Refund_Amount           235
Currency                 19
Country                   0
State                     0
Postal_Code              21
Sales_Channel            10
Payment_Method            0
Payment_Status            0
Status                    0
Promotion_Code          362
Promotion_Status        390
Campaign_ID             376
Return_Reason_Code      489
Tracking_ID             135
Carrier                  13
Delivery_Status          39
Email                    19
Phone_Number             91
Device                   99
Acquisition_Channel      68
Normalized_Qty            6
Normalized_Unit          50
Date                    114
Rate_INR                551
Amount_INR              553
Review_Flag               0
Tracking_Review           0
Refund_Ratio            346
Category_Review           0
Supplier_Review           0
Inventory_Review          0
dtype: int64

Fill missing text values with "Unknown"

In [1008]:
text_columns = ["Country", "State", "Sales_Channel",
                "Payment_Method", "Payment_Status"]

for col in text_columns:
    df[col] = df[col].fillna("Unknown")

In [1009]:
print("Missing discounts:", df["Discount"].isnull().sum())
print("Missing customer IDs:", df["Customer_ID"].isnull().sum())
print(df.isnull().sum())

Missing discounts: 177
Missing customer IDs: 2
Order_ID                  0
Line_ID                  19
Event_Version             0
Customer_ID               2
Master_Customer_ID       84
Transaction_ID           33
Visitor_ID               21
Session_ID               22
Event_Type                0
Order_TS                114
Event_TS                120
Shipment_TS              44
Delivery_TS              44
Expected_Delivery_TS      0
Product                   0
SKU                       0
Product_Category          0
Brand                     0
Supplier_ID              10
Inventory_ID              9
Stock_Quantity           36
Qty                       6
Unit                     50
Unit_Price              232
Discount                177
Tax                     148
Shipping_Cost           293
Line_Total                0
Amount                  203
Refund_Amount           235
Currency                 19
Country                   0
State                     0
Postal_Code              21
Sales_Channel             0
Payment_Method            0
Payment_Status            0
Status                    0
Promotion_Code          362
Promotion_Status        390
Campaign_ID             376
Return_Reason_Code      489
Tracking_ID             135
Carrier                  13
Delivery_Status          39
Email                    19
Phone_Number             91
Device                   99
Acquisition_Channel      68
Normalized_Qty            6
Normalized_Unit          50
Date                    114
Rate_INR                551
Amount_INR              553
Review_Flag               0
Tracking_Review           0
Refund_Ratio            346
Category_Review           0
Supplier_Review           0
Inventory_Review          0
dtype: int64

# 20. Flag out-of-order events and reconcile late-arriving order, payment, shipment, and return updates.

Convert date columns to datetime

In [1010]:
df["Order_TS"] = pd.to_datetime(df["Order_TS"], errors="coerce", utc=True)
df["Event_TS"] = pd.to_datetime(df["Event_TS"], errors="coerce", utc=True)
df["Shipment_TS"] = pd.to_datetime(df["Shipment_TS"], errors="coerce", utc=True)
df["Delivery_TS"] = pd.to_datetime(df["Delivery_TS"], errors="coerce", utc=True)

 Flag events before the order

In [1011]:
df["Event_Review"] = df["Event_TS"] < df["Order_TS"]

Flag shipments before the order

In [1012]:
df["Shipment_Review"] = df["Shipment_TS"] < df["Order_TS"]

Flag deliveries before shipment

In [1013]:
df["Delivery_Review"] = df["Delivery_TS"] < df["Shipment_TS"]

Display records needing review

In [1014]:
df[
    df["Event_Review"] |
    df["Shipment_Review"] |
    df["Delivery_Review"]
][[
    "Order_ID", "Order_TS", "Event_TS",
    "Shipment_TS", "Delivery_TS"
]]

,Order_ID,Order_TS,Event_TS,Shipment_TS,Delivery_TS
603,ORD-1240,2026-06-22 05:01:00+00:00,2026-06-21 23:58:00+00:00,2026-06-22 21:01:00+00:00,2026-06-29 15:31:00+00:00
599,ORD-1330,2026-09-19 16:31:00+00:00,2026-09-19 11:04:00+00:00,NaT,NaT
21,ORD-1224,2026-09-17 22:20:00+00:00,2026-09-17 20:31:00+00:00,2026-09-18 16:20:00+00:00,NaT
16,ORD-1143,2026-03-09 18:39:00+00:00,2026-03-09 13:54:00+00:00,NaT,NaT
596,ORD-1050,2026-07-13 19:56:00+00:00,2026-07-13 14:56:00+00:00,NaT,NaT
...,...,...,...,...,...
33,ORD-1242,2026-12-08 05:17:00+00:00,2026-08-12 06:25:00+00:00,NaT,NaT
70,ORD-1203,2026-08-19 05:27:00+00:00,2026-08-19 01:19:00+00:00,NaT,NaT
68,ORD-1131,2026-04-06 02:41:00+00:00,2026-04-05 21:47:00+00:00,NaT,NaT
65,ORD-1140,2026-08-21 00:30:00+00:00,2026-08-20 22:30:00+00:00,NaT,2026-08-27 09:00:00+00:00
525,ORD-1285,2026-03-31 00:09:00+00:00,2026-03-30 23:01:00+00:00,NaT,NaT

In [1015]:
print("Events before order:", df["Event_Review"].sum())
print("Shipments before order:", df["Shipment_Review"].sum())
print("Deliveries before shipment:", df["Delivery_Review"].sum())

Events before order: 106
Shipments before order: 1
Deliveries before shipment: 1

In [1016]:
df.tail()

,Order_ID,Line_ID,Event_Version,Customer_ID,Master_Customer_ID,Transaction_ID,Visitor_ID,Session_ID,Event_Type,Order_TS,...,Amount_INR,Review_Flag,Tracking_Review,Refund_Ratio,Category_Review,Supplier_Review,Inventory_Review,Event_Review,Shipment_Review,Delivery_Review
583,ORD-1081,L1,3,CUST-040,CUST-040,TXN53335744,VIS-46007,SES-116619,payment_failed,2026-08-26 21:11:00+00:00,...,NaN,False,False,NaN,False,False,False,False,False,False
525,ORD-1285,L1,4,CUST-020,CUST-020,TXN-51142480,VIS-24033,SES-901856,cancel,2026-03-31 00:09:00+00:00,...,NaN,False,True,0.0,False,True,False,True,False,False
258,ORD-1269,L1,4,CUST-060,CUST-060,TXN-63226396,VIS-86545,SES-721814,purchase,2026-08-21 18:06:00+00:00,...,NaN,False,False,NaN,False,False,False,False,False,False
180,ORD-1225,L2,4,CUST-036,CUST-036,TXN-14657496,VIS-50484,SES-611915,refund_request,2026-09-17 08:46:00+00:00,...,NaN,False,False,NaN,False,False,False,False,False,False
579,ORD-1259,LINE-1,4,CUST-050,CUST-050,TXN20892215,VIS-25331,SES-342328,payment_success,2026-09-07 08:08:00+00:00,...,NaN,False,False,0.0,False,False,False,False,False,False

In [1017]:
for col in df.columns:
    if isinstance(df[col].dtype, pd.DatetimeTZDtype):
        df[col] = df[col].astype(str)


df.to_csv("r-ecommerce_Cleaned.csv", index=False)

print("File saved with time zones!")

File saved with time zones!